# Generated by Django 5.0.7 on 2024-07-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_productos_options_remove_productos_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categoria_productos',
            new_name='CategoriaProducto',
        ),
        migrations.RenameModel(
            old_name='productos',
            new_name='Producto',
        ),
        migrations.AlterModelOptions(
            name='categoriaproducto',
            options={'verbose_name': 'CategoriaProducto', 'verbose_name_plural': 'CategoriasProductos'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
